### PR TITLE
Issue/15/binned cosmological analysis

### PR DESCRIPTION
**Pull request by payerne**
add the new data, modules and analysis codes for the cluster scaling relation in the main branch

### CODE REVIEW

**Review by combet — COMMENTED** [review]
There are temporary/hidden files/directories in various places should not be pushed into the repo, namely:
- `.ipynb_checkpoints`
- `__pycache__`

I also saw `trash`, `old`, `Logs` directories, which were probably not meant to be pushed?

**Comment by payerne** [comment]
I removed all (I guess) the .ipynb_checkpoints and pycache files. The /old and /trash files contain old codes, that I still want to check before removing them.

**Comment by combet** [comment]
Thanks @payerne. There is still one hidden checkpoint directory in the `old_files` folder. Also, the `Logs` directory with the log of all the jobs you ran should not be pushed to the repo.

**Comment by payerne** [comment]
I removed the remaining .ipynb_checkpoints file and the /Logs directory.

**Review by combet — APPROVED** [review]
Thanks for the changes @payerne!

**Pull request merged**
